#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#authentication_token:
#  path: /authentication_token
#  methods: ['POST']

register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: [POST]

api:
  path: /api
  controller: App\Controller\AuthController::api

login_check:
  path: /api/login_check
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }