vich_uploader:
    db_driver: orm

    mappings:
        projectImages:
            uri_prefix: /images/projectImages
            upload_destination: '%kernel.project_dir%/public/images/projectImages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        receiptFiles:
            uri_prefix: /files/receipts
            upload_destination: '%kernel.project_dir%/public/files/receipts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        agreementFiles:
            uri_prefix: /files/project-agreements
            upload_destination: '%kernel.project_dir%/public/files/project-agreements'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        commentImages:
            uri_prefix: /images/commentImages
            upload_destination: '%kernel.project_dir%/public/images/commentImages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        usersImages:
            uri_prefix: /images/usersImages
            upload_destination: '%kernel.project_dir%/public/images/usersImages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        ministryImages:
            uri_prefix: /images/ministryImages
            upload_destination: '%kernel.project_dir%/public/images/ministryImages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer